const {
  PROJECT_ID,

  TIMEOUT,
  HISTORY_ACTIVE,
  HISTORY_PRUNE_INTERVAL,

  LOG_LEVEL = 'info',
  ENABLE_PRETTY_PRINT = false,

  SNEEZE_SILENT = false,
  SWIM_INTERVAL = 500,
  SWIM_JOIN_TIMEOUT = 2000,
  SWIM_PING_TIMEOUT = 2000,
  SWIM_PING_REQUEST_TIMEOUT = 2000
} = process.env

module.exports = {
  PROJECT_ID,

  TIMEOUT,
  HISTORY_ACTIVE,
  HISTORY_PRUNE_INTERVAL,

  LOG_LEVEL,
  ENABLE_PRETTY_PRINT,

  SNEEZE_SILENT,
  SWIM_INTERVAL,
  SWIM_JOIN_TIMEOUT,
  SWIM_PING_TIMEOUT,
  SWIM_PING_REQUEST_TIMEOUT
}
